### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [hzi-bifo/Phylogeography_Paper#1]
Rscript phylogeo_sankoff.R ../../Data/Simulations/Sim_1/simulated_seq_cds.labeled.phy ../../Data/Simulations/Sim_1/tipdata.txt /path/to/effective.distance.matrix.csv reconstruction_effective

Could you tell me where to find the effective.distance.matrix.csv file, thansk.

**Comment by BEAST-Community** [comment]
another question, could you please tell me why location A to B is different from location B to A, in the distance.matrix.csv file of testdata, thanks.

**Comment by liamxg** [comment]
another question, could you please tell me why the distance matrix value location A to B is different from location B to A, in the distance.matrix.csv file of testdata, thanks.

**Comment by BEAST-Community** [comment]
Rscript create_favites_input.R $transmissions $num_transmissions
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file '200': No such file or directory
Execution halted

**Comment by SusanneReimering** [comment]
Hi @LiXingguangBrandonStark, all distance matrices can be found at https://zenodo.org/record/2643163#.YDjgCNYo9hF. The reconstruction also works on asymmetrical distances (e.g. effective distances), which is why the distances from A to B are different to the distances from B to A in the example data.

**Comment by SusanneReimering** [comment]
Hi @BEAST-Community, it looks like your input file that should contain the transmissions as output by Gleamviz was not found. Can you please check if the file that you're providing when calling the simulation_pipeline.sh script is at the correct location and give me more information on the commands you used if you're still having problems?

**Comment by liamxg** [comment]
@SusanneReimering, i use your data and code, they are still have problems, could you tell me your email, please.

**Comment by liamxg** [comment]
could you tell me the data that should be input for the "label_internal_nodes.R" file, thanks. i am very confused, and this is very important to me, thanks.

**Comment by SusanneReimering** [comment]
Hi @LiXingguangBrandonStark, please let me know how you're calling the script that you're having problems with and what exactly the output looks like. I tried running the code again using the instructions and data in this repository and can't replicate any errors. 
The script label_internal_nodes.R should take the tree and transmission network as generated by Favites, the metadata from the GleamViz output as well as the name of the output folder as input. You shouldn't have to use this script separately though, as this is done automatically when you're using the simulation_pipeline.sh script.
My email is Susanne.Reimering@helmholtz-hzi.de, you can contact me there if that's easier for you.

**Comment by liamxg** [comment]
(base) lixingguangtekiMacBook-puro:Simulation lixingguang$ bash simulation_pipeline.sh ../../Data/Gleamviz/seedings.tsv ../../Data/Gleamviz/metadata_cities.tsv ./run_favites_docker.py ../../Data/FAVITES/flu_spread_config.json simulation_output
Traceback (most recent call last):
  File "./run_favites_docker.py", line 105, in <module>
    o = check_output(['docker','images']).decode().splitlines()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
gunzip: can't stat: FAVITES_output/error_free_files/sequence_data.fasta.gz (FAVITES_output/error_free_files/sequence_data.fasta.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/error_free_files/transmission_network.txt.gz (FAVITES_output/error_free_files/transmission_network.txt.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/error_free_files/phylogenetic_trees/tree_0.tre.gz (FAVITES_output/error_free_files/phylogenetic_trees/tree_0.tre.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/error_free_files/phylogenetic_trees/tree_0.time.tre.gz (FAVITES_output/error_free_files/phylogenetic_trees/tree_0.time.tre.gz.gz): No such file or directory
gunzip: can't stat: FAVITES_output/seed_sequences.tsv.gz (FAVITES_output/seed_sequences.tsv.gz.gz): No such file or directory
Error in file(file, "r") : cannot open the connection
Calls: read.tree -> scan -> file
In addition: Warning message:
In file(file, "r") :
  cannot open file 'FAVITES_output/error_free_files/phylogenetic_trees/tree_0.tre': No such file or directory
Execution halted
cp: FAVITES_output/error_free_files/sequence_data.fasta: No such file or directory
head: FAVITES_output/seed_sequences.tsv: No such file or directory
head: FAVITES_output/seed_sequences.tsv: No such file or directory
(base) lixingguangtekiMacBook-puro:Simulation lixingguang$
